# batch config

label:              '2024-KC-NARA'
description:        'NARA A-Files for Migrants and the State Project'
attribution:        ''
source_dir:         '/Volumes/migrants_state/2024-KC-NARA/jpgs'

presentation_api_url: 'https://aperitiiif-presentation-api-store.s3.us-east-1.amazonaws.com'
image_api_url:        'https://d1b7k5w7yjwpfg.cloudfront.net/iiif/2'

records:
  file: 'src/afiles.csv'
